language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false
dist: xenial

addons:
  apt:
    packages:
    - shellcheck

script:
    - make test
    # I hope to enable shellcheck one day
    #- bash -c 'find . -type f -name "*.sh"  | xargs shellcheck'

matrix:
  fast_finish: true
notifications:
  email: false
